#!/bin/bash
# Quick reference for pushing to GitHub

echo "=== HSC-ESP32-Base: GitHub Push Commands ==="
echo ""
echo "1. Stage all changes:"
echo "   git add ."
echo ""
echo "2. Commit changes:"
echo "   git commit -m \"Refactor to reusable library structure - v0.1.0\""
echo ""
echo "3. Tag the release:"
echo "   git tag -a v0.1.0 -m \"Initial release of HSC-ESP32-Base library\""
echo ""
echo "4. Add GitHub remote (replace YOUR_USERNAME):"
echo "   git remote add origin https://github.com/YOUR_USERNAME/HSC-ESP32-Base.git"
echo ""
echo "5. Push to GitHub:"
echo "   git push -u origin main"
echo "   git push --tags"
echo ""
echo "=== Done! ==="
